#Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
#Fabric Properties
minecraft_version=1.21.11
loader_version=0.18.5
loom_version=1.15-SNAPSHOT
# Mod Properties
mod_id=quickwarp-odin
mod_name=QuickWarp
mod_description=A Hypixel Skyblock Odin addon that adds different modes for Etherwarp.
mod_version=0.0.1
maven_group=com.odtheking
archives_base_name=quickwarp
# Mod Dependencies
fabric_kotlin_version=1.13.10+kotlin.2.3.20
fabric_api_version=0.141.3+1.21.11
devauth_version=1.2.2
commodore_version=1.0.1
# Other Properties
kotlin_version=2.3.20
kotlin.code.style=official
minecraft_lwjgl_version=3.3.3

# you can put here either version number (0.0.4) or commit hashes
odin_version=0.1.9